apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: smpp-producer

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/version: "2.0.1"

images:
  - name: smpp-kafka-producer
    newTag: latest
